{% set version = "1.0.0" %}
{% set python_min = "3.11" %}

package:
  name: earthkit-meteo
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/earthkit-meteo/earthkit_meteo-{{ version }}.tar.gz
  sha256: e80c6e8d0ca1492d6f9e0c607132ce008c7ebfea3c32d55a00101bdc36ada178

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation"
  number: 0

requirements:
  host:
    - python {{ python_min }}.*
    - setuptools >=61
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - earthkit-utils >=0.2,<0.99
    - numpy

test:
  imports:
    - earthkit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ecmwf/earthkit-meteo/
  summary: Meteorological computations
  doc_url: https://earthkit-meteo.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tjtg
    - jasonjunweilyu
    - HCookie
