schema_version: 1

context:
  version: "1.1.1"

package:
  name: earthkit-meteo
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/earthkit-meteo/earthkit_meteo-${{ version }}.tar.gz
  sha256: 49719b29abd063ed62f94a3ae104398eb1147852a1d93b5be56ca60669c4b94c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - deprecation
    - earthkit-utils ~=1.0
    - numpy

tests:
  - python:
      imports:
        - earthkit
        - earthkit.meteo.wind
        - earthkit.meteo.thermo
        - earthkit.meteo.constants
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Meteorological computations
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/ecmwf/earthkit-meteo/
  documentation: https://earthkit-meteo.readthedocs.io/

extra:
  recipe-maintainers:
    - tjtg
    - jasonjunweilyu
    - HCookie
