schema_version: 1

context:
  version: "1.2.0"
  python_min: "3.11"

package:
  name: earthkit-meteo
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/e/earthkit-meteo/earthkit_meteo-${{ version }}.tar.gz
  sha256: 239c89dbf30ee3d64f7e2df700b5e20077ca1cd35db9a66ba0fb79ddcd871d11

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - earthkit-utils >=0.2,<0.99
    - numpy

tests:
  - python:
      imports:
        - earthkit
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Meteorological computations
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/ecmwf/earthkit-meteo/
  documentation: https://earthkit-meteo.readthedocs.io/

extra:
  recipe-maintainers:
    - tjtg
    - jasonjunweilyu
    - HCookie
